version: '3'
services:
      titanic-db:
            image: my-mysql:v1.5.0
            build: .
            volumes:
            - /my-mysql:/var/lib/mysql
            ports:
            - "3600:3600"
            restart: always
            environment:
                    MYSQL_ROOT_PASSWORD: my_secret
                    MYSQL_DATABASE: titanic_survivor_data
                    MYSQL_USER: mysql_user
                    MYSQL_PASSWORD: user_password  
      titanic-api:
            image: my-api:v1.0.0
            build: api/
            depends_on:
            - titanic-db
            ports:
            - "4000:4000"
            restart: always
            environment:
                    MYSQL_DB_HOST: titanic-db
                    MYSQL_DB: titanic_survivor_data
                    MYSQL_PORT: 3306
                    MYSQL_USER: mysql_user
      promtheus:
            image: prom/prometheus:v2.26.0
            volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            ports:
            - "9000:9000"
      grafanna:
            image: grafana/grafana:7.5.2
            volumes:
            - ./datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
            ports:
            - "3000:3000"

