crape_configs:
        - job_name: my-mysql
          metrics_path: /metrics
          static_configs:
                  - targets:
                    - 172.17.0.1:3600  # replace ip address with the ip of the database
