apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: contsolutions
  name: sqlservice
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 30180
  selector:
    app: contsolutions
status:
  loadBalancer: {}
